### ISSUE TITLE
search results should have a list header

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#165]
The `Pack` sound list has a title but the search results list doesn't:

## Pack SoundList

<img width="741" alt="Screen Shot 2020-11-10 at 12 44 56 PM" src="https://user-images.githubusercontent.com/6374832/98731385-8a544100-2352-11eb-8e68-34bed01a2b8c.png">

## Search Results SoundList

<img width="602" alt="Screen Shot 2020-11-10 at 12 43 59 PM" src="https://user-images.githubusercontent.com/6374832/98731319-6abd1880-2352-11eb-8346-af836ead60ec.png">

**Comment by hamirmahal** [comment]
I think we can do this with a small change to [`SoundList.js`](https://github.com/amilajack/freesound-player/blob/master/src/SoundList.js) on [line 9](https://github.com/amilajack/freesound-player/blob/0032de3eeccba9e80bcd6266ba8e9e0842507876/src/SoundList.js#L9).

```
      {header ? (
        <h1 className="text-3xl m-auto py-4">{header}</h1>
      ) : (
        <h1 className="text-3xl m-auto py-4">Search results</h1>
      )}
```

One drawback might be that users will see "Search results" at the top of the home page on the initial visit to the application, even before searching anything.

**Comment by hamirmahal** [comment]
If we want to be more "fancy", we can add an additional prop to the `SoundList` component that corresponds to the input typed into the search bar, so the page displays "Search results for " + inputUserEntered. The screenshot at the end of this comment illustrates this.

To do that, we could modify [line 6 of `SoundList.js`](https://github.com/amilajack/freesound-player/blob/0032de3eeccba9e80bcd6266ba8e9e0842507876/src/SoundList.js#L6) to have something like

`const SoundList = ({ tracks, header, onSoundClick,`**`searchParam={searchValue}`**`}) => {`.

We would also make changes similar to the code block above.

```
      {header ? (
        <h1 className="text-3xl m-auto py-4">{header}</h1>
      ) : (
        <h1 className="text-3xl m-auto py-4">
          Search results for {searchParam}
        </h1>
      )}
```

If we take this approach, [`SearchResults.js`](https://github.com/amilajack/freesound-player/blob/master/src/SearchResults.js) would also take a `searchParam` prop that we could pass to it on [line 35](https://github.com/amilajack/freesound-player/blob/0032de3eeccba9e80bcd6266ba8e9e0842507876/src/SearchResults.js#L35), e.g.,

`return <SoundList tracks={searchResults}`**`searchParam={searchValue}`**`/>;`.

But, this might be redundant, since users would already know what query they just typed into the search box and they can see the search box immediately in the upper-righthand corner of the page. I also don't see this approach for displaying search results in the searches I performed on three major websites. What do you think?

![Screen Shot 2020-11-10 at 11 12 11 PM](https://user-images.githubusercontent.com/43425812/98780786-2cebde80-23aa-11eb-8aa9-58920acec53c.png)

**Comment by amilajack** [comment]
I think this is change should be only a one liner:

```diff
-   return <SoundList tracks={searchResults} />;
+  return <SoundList header={`Search results for ${searchQuery}`} tracks={searchResults} />;
```

**Comment by hamirmahal** [comment]
> I think implementing this is change should be only a one liner:
> 
> ```diff
> -  return <SoundList tracks={searchResults} />;
> +  return <SoundList header={`Search results for "${searchQuery}"`} tracks={searchResults} />;
> ```

Nice! This is even cleaner than what I had, and I thought that was minimal, already.

The only thing I think needs to be different is `searchQuery` should be `searchValue`, and it works.

`prettier` wants the return statement across multiple lines, so it ends up looking like this:

```
  return (
    <SoundList
      header={`Search results for "${searchValue}"`}
      tracks={searchResults}
    />
  );
```

Users might wonder why the first thing they see when they open the application are search results for "note", but I think that's outside the scope of this issue. We can probably create a separate ticket for creating a new homepage.

![Screen Shot 2020-11-11 at 11 21 40 AM](https://user-images.githubusercontent.com/43425812/98854926-14161400-2410-11eb-8553-c588c015bc85.png)

**Comment by amilajack** [comment]
Nice! PR the fix and we can close this!
