### ISSUE TITLE
sound description doesn't change on certain tracks

### ISSUE THREAD

**Issue by akshara-sun** [amilajack/freesound-player#175]
On the Home page, there are a list of sounds including  _Music Note 5_, _Music Note 9_, _Music Note 4_, _Music Note 6_, and _Music Note 8_. When you click on these spefic tracks, the description for those do not change.

**Comment by hamirmahal** [comment]
I think [Music Note 5](https://freesound-player.vercel.app/sound/462807), [Music Note 9](https://freesound-player.vercel.app/sound/462808), [Music Note 4](https://freesound-player.vercel.app/sound/462800), [Music Note 6](https://freesound-player.vercel.app/sound/462806), and [Music Note 8 on our application](https://freesound-player.vercel.app/sound/462804) don't change descriptions because the user who uploaded those sounds didn't update the descriptions for [Music Note 5](https://freesound.org/people/qfox123/sounds/462807/), [Music Note 9](https://freesound.org/people/qfox123/sounds/462808/), [Music Note 4](https://freesound.org/people/qfox123/sounds/462800/), [Music Note 6](https://freesound.org/people/qfox123/sounds/462806/) and [Music Note 8 on the site from which we pull sounds and their descriptions](https://freesound.org/people/qfox123/sounds/462804/). Our application currently just pulls whatever it sees from freesound, and the user who uploaded the five sounds you mentioned on freesound put the exact same description for each sound, which is why it appears the description doesn't change between those five tracks on our application.

# Music Note 5 on freesound
![Music Note 5 on freesound](https://user-images.githubusercontent.com/43425812/99112264-3fc90380-25a2-11eb-9a8c-8bcfd295e943.png)

# Music Note 9 on freesound
![Music Note 9 on freesound](https://user-images.githubusercontent.com/43425812/99112413-7dc62780-25a2-11eb-830f-fb4c10f554eb.png)

# Music Note 4 on freesound
![Music Note 4 on freesound](https://user-images.githubusercontent.com/43425812/99112452-89195300-25a2-11eb-9d99-6eb63b839c64.png)

# Music Note 6 on freesound
![Music Note 6 on freesound](https://user-images.githubusercontent.com/43425812/99112466-90406100-25a2-11eb-98cc-71548060ccd7.png)

# Music Note 8 on freesound
![Music Note 8 on freesound](https://user-images.githubusercontent.com/43425812/99112496-96ced880-25a2-11eb-866c-8c0421e9552f.png)

**Comment by amilajack** [comment]
Good catch Hamir! I suspected this was a bug since we're pretty early in development but didnt even stop to think about something as simple as the description literally just being the same! Good catch! 💯

**Comment by hamirmahal** [comment]
Thanks! Glad I was able to help.
