### ISSUE TITLE
implement home page banner

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#181]
<img width="1413" alt="Screen Shot 2020-11-14 at 12 21 16 PM" src="https://user-images.githubusercontent.com/6374832/99156195-e6c9a000-2673-11eb-9a0d-e7b5f15ffebc.png">

**Comment by akshara-sun** [comment]
I think this is a great idea. My take is that we should display the banner for first-time users ONLY. Those who are regular users don't need to see the banner because they wouldn't be regular users if they don't know what Tide is about so I propose that once the user logs in, we could remove the banner and/or display something else.
